### PR TITLE
Fix attractors example parameter value

### PR DESCRIPTION
**Pull request by jbednar**
The main fix is in https://github.com/pyviz-topics/examples/commit/970d0f8b9eeeb901ef761ccb94810891adb3d535 , where somehow a "2" in my original project https://anaconda.org/jbednar/project/attractors became a "-11", which is not a valid value for a Hopalong attractor.

Also reformatted the .yml so that it's easier to skim and edit, and fixed a warning from IPython for `display`.

### CODE REVIEW

**Comment by Azaya89** [comment]
Is it possible to add this fix to this current PR #381 ?
@jbednar

**Comment by maximlt** [comment]
@Azaya89 please incorporate the changes made by this PR in your branch. That will nicely format the yaml file and fix a bug.

**Comment by Azaya89** [comment]
> @Azaya89 please incorporate the changes made by this PR in your branch. That will nicely format the yaml file and fix a bug.

Done!

**Comment by jbednar** [comment]
Sounds good, thanks! Sorry for letting this PR get stale and thus cause problems; I have no idea why it wasn't merged two years ago!

@Azaya89 , I agree with @maximlt that it's easier just to re-create these specific changes in your other PR, rather than try to rebase or merge on this PR. I'd delete those rebase commits and just start fresh, because I'm not seeing these changes show up in the diffs for https://github.com/holoviz-topics/examples/pull/381 , and instead there are various unrelated things showing up in the diffs that I'm not sure should be there. Can you just delete commits 561469837ef14cb299555f4565334d64875de90b and 4745dc9abee676fc91e15443c29781b75baefc0f and try again?  Meanwhile I'll close this PR, as your PR will be the one we'll take forward.

**Pull request closed without merging**
