### PR TITLE
[DO NOT MERGE] Isaiah's Dummy example

### PR DESCRIPTION
**Pull request by Azaya89**
I created a dummy example in order to verify all the steps required in creating a new example project from scratch, per https://examples.holoviz.org/contributing.html#add-a-project

I think the only thing we need to modify in the instructions is explicitly mentioning that the `doit` commands should be run from the top level of the repository. Otherwise, everything else is clear and straight-forward.

### CODE REVIEW

**Review by maximlt — CHANGES_REQUESTED** [review]
I'm impressed it went so smoothly :)

Could you update this example to include a deployable panel app? I.e:
- the notebook must contain something like `<app>.servable()`
- the project YAML must be updated with a new `dashboard` command and that command must be specified in `examples_config.deployments`

**Comment by droumis** [comment]
Nice work! Do you want to add the suggestion for the instructions to your contributing guide PR?

**Comment by Azaya89** [comment]
> Nice work! Do you want to add the suggestion for the instructions to your contributing guide PR?

Yes, I will do that tomorrow.

**Comment by maximlt** [comment]
You did great creating this dummy example! I'm going to close this PR now (we can still re-open it later if need be).

**Pull request closed without merging**
