### PR TITLE
Modernize penguins example and compliance

### PR DESCRIPTION
**Pull request by philippjfr**
- [x] Made plots height responsive
- [x] Switched to FastListTemplate
- [ ] Fix selection on violin
- [x] Clean up sidebar
- [ ] Add clear button

Screen Shot 2022-12-19 at 02 03 55

### CODE REVIEW

**Comment by Hoxbro** [comment]
Just noting, I can't use lasso select on the current [Palmer Panguins](https://penguin-crossfilter.pyviz.demo.anaconda.com/penguin_crossfilter)

**Comment by MarcSkovMadsen** [comment]
The issue a reported bug with HoloViews on this.

**Comment by philippjfr** [comment]
Works fine in the version I have checked in here.

**Comment by maximlt** [comment]
Just noting that there was indeed an issue opened on HoloViews on this, and it was found that this was because the element used was Scatter instead of Points.

**Pull request merged**
