### PR TITLE
Add sorting by last updated date or title

### PR DESCRIPTION
**Pull request by droumis**
This won't look like it's working yet on the deployed site because of https://github.com/holoviz-topics/examples/issues/374

But here it is working on my local build:

https://github.com/user-attachments/assets/c21ad992-fa24-41e3-a8ed-94206ab0e0dd

### CODE REVIEW

**Comment by jlstevens** [comment]
Thank you!

Having the option to sort will make the tile view even more useful. Sorting by name and last updated are the most important things but if we have the metadata for it, we can also imagine sorting by author name, creation date etc.

**Comment by droumis** [comment]
> Thank you!
> 
> Having the option to sort will make the tile view even more useful. Sorting by name and last updated are the most important things but if we have the metadata for it, we can also imagine sorting by author name, creation date etc.

Sure, but in future PRs

**Comment by droumis** [comment]
alright to merge?

**Comment by jlstevens** [comment]
Thanks!

**Pull request merged**
